---
title: "Skistodiaptomus Thermal Acclimation with MicroPlastics"
date: last-modified 
date-format: "YYYY-MM-DD" 
title-block-published: "Updated"
toc: true
format:
  html:
    anchor-sections: false
    other-links:
      - text: Project Repo
        href: https://github.com/ZoopEcoEvo
editor: 
  markdown: 
    wrap: 72
---

## Project Description

This experiment examines how exposure to microplastics levels affect the thermal tolerance (Critical
Thermal Maximum; CTmax) and acclimation capacity of Skistodiaptomus
pallidus (S. pallidus) under ambient and elevated temperature
conditions relevant to heatwave predictions.

We will use a factorial design and a one week treatment period, with
groups exposed to control conditions (16°C, No microplastics), a microplastics
treatment (16°C with microplastics), a heatwave treatment (22°C and no microplastics), and a
combined treatment with both microplasti4cs and heatwave conditions.
Results will improve our understanding of copepod resilience in a
warming, plastic-polluted world by XYZ.

## Questions, Objectives, Hypotheses

Questions:

1.  How does exposure to end-of-century concentrations of MPs affect the
    thermal tolerance of S. pallidus?

2.  Do MPs affect S. pallidus ability to acclimate to end-of-century
    heatwave temperatures?

Hypotheses:

1.  Exposure to end-of-century concentrations of MPs will cause an
    increase in thermal tolerance because of stress pathways are
    activated by the MPs, priming organisms to respond to thermal
    stress.
2.  MPs will increase S. pallidus's acclimation ability to
    end-of-century heatwave temperatures.

## Variable Descriptions

+------+------+------+------+------+------+------+------+
| Var  | Var  | Res  | Rel  | Data | U    | Exp  | How  |
| i    | i    | p    | e    | Type | nits | e    | are  |
| able | able | onse | vant |      |      | cted | z    |
| Name | D    | or   | Que  |      |      | R    | eros |
|      | e    | Ex   | s    |      |      | ange | and  |
|      | scri | p    | tion |      |      |      | mi   |
|      | p    | lana | or   |      |      |      | s    |
|      | tion | t    | Obje |      |      |      | sing |
|      |      | ory? | c    |      |      |      | data |
|      |      |      | tive |      |      |      | reco |
|      |      |      |      |      |      |      | r    |
|      |      |      |      |      |      |      | ded? |
+======+======+======+======+======+======+======+======+
| |    | Cri  | Depe | 1 &  | Num  | De   | 2    | NA   |
|      | t    | n    | 2    | eric | g    | 5    |      |
| C    | ical | dent |      |      | rees | °C - |      |
| Tmax | th   |      |      |      | C    | 45°C |      |
|      | e    |      |      |      |      |      |      |
|      | rmal |      |      |      |      |      |      |
|      | ma   |      |      |      |      |      |      |
|      | x    |      |      |      |      |      |      |
|      | ima, |      |      |      |      |      |      |
|      | the  |      |      |      |      |      |      |
|      | u    |      |      |      |      |      |      |
|      | pper |      |      |      |      |      |      |
|      | th   |      |      |      |      |      |      |
|      | e    |      |      |      |      |      |      |
|      | rmal |      |      |      |      |      |      |
|      | l    |      |      |      |      |      |      |
|      | imit |      |      |      |      |      |      |
|      | of   |      |      |      |      |      |      |
|      | an   |      |      |      |      |      |      |
|      | orga |      |      |      |      |      |      |
|      | n    |      |      |      |      |      |      |
|      | ism, |      |      |      |      |      |      |
|      | rec  |      |      |      |      |      |      |
|      | o    |      |      |      |      |      |      |
|      | rded |      |      |      |      |      |      |
|      | when |      |      |      |      |      |      |
|      | the  |      |      |      |      |      |      |
|      | a    |      |      |      |      |      |      |
|      | n    |      |      |      |      |      |      |
|      | imal |      |      |      |      |      |      |
|      | s    |      |      |      |      |      |      |
|      | tops |      |      |      |      |      |      |
|      | r    |      |      |      |      |      |      |
|      | espo |      |      |      |      |      |      |
|      | n    |      |      |      |      |      |      |
|      | ding |      |      |      |      |      |      |
|      | to   |      |      |      |      |      |      |
|      | st   |      |      |      |      |      |      |
|      | i    |      |      |      |      |      |      |
|      | muli |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+
| T    | Co   | I    | 1 &  | C    | De   | *    | T    |
| e    | n    | n    | 2    | a    | g    | *Put | here |
| mper | trol | depe |      | tego | rees | the  | s    |
| a    | (    | n    |      | r    | C    | v    | h    |
| ture | 16C) | dent |      | ical |      | a    | ould |
| Trea | or   |      |      |      |      | lues | be   |
| t    | Warm |      |      |      |      | h    | no   |
| ment | (    |      |      |      |      | e    | mi   |
|      | 2    |      |      |      |      | re** | s    |
|      | 2C), |      |      |      |      |      | sing |
|      | a    |      |      |      |      |      | v    |
|      | c    |      |      |      |      |      | a    |
|      | clim |      |      |      |      |      | lues |
|      | a    |      |      |      |      |      |      |
|      | tion |      |      |      |      |      |      |
|      | t    |      |      |      |      |      |      |
|      | e    |      |      |      |      |      |      |
|      | mper |      |      |      |      |      |      |
|      | a    |      |      |      |      |      |      |
|      | ture |      |      |      |      |      |      |
|      | for  |      |      |      |      |      |      |
|      | each |      |      |      |      |      |      |
|      | trea |      |      |      |      |      |      |
|      | t    |      |      |      |      |      |      |
|      | ment |      |      |      |      |      |      |
|      |      |      |      |      |      |      |      |
|      | *    |      |      |      |      |      |      |
|      | *Com |      |      |      |      |      |      |
|      | m    |      |      |      |      |      |      |
|      | ent: |      |      |      |      |      |      |
|      | Si   |      |      |      |      |      |      |
|      | m    |      |      |      |      |      |      |
|      | ilar |      |      |      |      |      |      |
|      | to   |      |      |      |      |      |      |
|      | "th  |      |      |      |      |      |      |
|      | e    |      |      |      |      |      |      |
|      | rmal |      |      |      |      |      |      |
|      | l    |      |      |      |      |      |      |
|      | i    |      |      |      |      |      |      |
|      | mit" |      |      |      |      |      |      |
|      | vs   |      |      |      |      |      |      |
|      | "th  |      |      |      |      |      |      |
|      | e    |      |      |      |      |      |      |
|      | rmal |      |      |      |      |      |      |
|      | t    |      |      |      |      |      |      |
|      | o    |      |      |      |      |      |      |
|      | lera |      |      |      |      |      |      |
|      | n    |      |      |      |      |      |      |
|      | ce", |      |      |      |      |      |      |
|      | try  |      |      |      |      |      |      |
|      | to s |      |      |      |      |      |      |
|      | t    |      |      |      |      |      |      |
|      | anda |      |      |      |      |      |      |
|      | r    |      |      |      |      |      |      |
|      | dize |      |      |      |      |      |      |
|      | wh   |      |      |      |      |      |      |
|      | e    |      |      |      |      |      |      |
|      | ther |      |      |      |      |      |      |
|      | we   |      |      |      |      |      |      |
|      | call |      |      |      |      |      |      |
|      | it   |      |      |      |      |      |      |
|      | "war |      |      |      |      |      |      |
|      | m    |      |      |      |      |      |      |
|      | ing" |      |      |      |      |      |      |
|      | or   |      |      |      |      |      |      |
|      | "h   |      |      |      |      |      |      |
|      | e    |      |      |      |      |      |      |
|      | atwa |      |      |      |      |      |      |
|      | v    |      |      |      |      |      |      |
|      | e"** |      |      |      |      |      |      |
+------+------+------+------+------+------+------+------+
| M i  | None | I    | 1 &  | C    | *    | *    | T    |
| c    | or   | n    | 2    | a    | *Put | *Put | here |
| ropl | MP   | depe |      | tego | the  | the  | s    |
| a    |      | n    |      | r    | v    | v    | h    |
| stic |      | dent |      | ical | a    | a    | ould |
| Trea |      |      |      |      | lues | lues | be   |
| t    |      |      |      |      | h    | h    | no   |
| ment |      |      |      |      | e    | e    | mi   |
|      |      |      |      |      | re** | re** | s    |
|      |      |      |      |      |      |      | sing |
|      |      |      |      |      |      |      | v    |
|      |      |      |      |      |      |      | a    |
|      |      |      |      |      |      |      | lues |
+------+------+------+------+------+------+------+------+
| Tube |      |      |      |      |      |      | T    |
|      |      |      |      |      |      |      | here |
|      |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | h    |
|      |      |      |      |      |      |      | ould |
|      |      |      |      |      |      |      | be   |
|      |      |      |      |      |      |      | no   |
|      |      |      |      |      |      |      | mi   |
|      |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | sing |
|      |      |      |      |      |      |      | v    |
|      |      |      |      |      |      |      | a    |
|      |      |      |      |      |      |      | lues |
+------+------+------+------+------+------+------+------+
| T    |      |      |      |      |      |      | T    |
| h    |      |      |      |      |      |      | here |
| ermo |      |      |      |      |      |      | s    |
| m    |      |      |      |      |      |      | h    |
| eter |      |      |      |      |      |      | ould |
|      |      |      |      |      |      |      | be   |
|      |      |      |      |      |      |      | no   |
|      |      |      |      |      |      |      | mi   |
|      |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | sing |
|      |      |      |      |      |      |      | v    |
|      |      |      |      |      |      |      | a    |
|      |      |      |      |      |      |      | lues |
+------+------+------+------+------+------+------+------+
| W    |      |      |      |      |      |      | T    |
| ater |      |      |      |      |      |      | here |
| Bath |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | h    |
|      |      |      |      |      |      |      | ould |
|      |      |      |      |      |      |      | be   |
|      |      |      |      |      |      |      | no   |
|      |      |      |      |      |      |      | mi   |
|      |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | sing |
|      |      |      |      |      |      |      | v    |
|      |      |      |      |      |      |      | a    |
|      |      |      |      |      |      |      | lues |
+------+------+------+------+------+------+------+------+
| S    |      |      |      |      |      |      | T    |
| tart |      |      |      |      |      |      | here |
| Time |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | h    |
|      |      |      |      |      |      |      | ould |
|      |      |      |      |      |      |      | be   |
|      |      |      |      |      |      |      | no   |
|      |      |      |      |      |      |      | mi   |
|      |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | sing |
|      |      |      |      |      |      |      | v    |
|      |      |      |      |      |      |      | a    |
|      |      |      |      |      |      |      | lues |
+------+------+------+------+------+------+------+------+
| A    |      |      |      |      |      |      | T    |
| c    |      |      |      |      |      |      | here |
| clim |      |      |      |      |      |      | s    |
| a    |      |      |      |      |      |      | h    |
| tion |      |      |      |      |      |      | ould |
| Day  |      |      |      |      |      |      | be   |
|      |      |      |      |      |      |      | no   |
|      |      |      |      |      |      |      | mi   |
|      |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | sing |
|      |      |      |      |      |      |      | v    |
|      |      |      |      |      |      |      | a    |
|      |      |      |      |      |      |      | lues |
+------+------+------+------+------+------+------+------+
| E    |      |      |      |      |      |      | T    |
| xper |      |      |      |      |      |      | here |
| i    |      |      |      |      |      |      | s    |
| ment |      |      |      |      |      |      | h    |
| Date |      |      |      |      |      |      | ould |
|      |      |      |      |      |      |      | be   |
|      |      |      |      |      |      |      | no   |
|      |      |      |      |      |      |      | mi   |
|      |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | sing |
|      |      |      |      |      |      |      | v    |
|      |      |      |      |      |      |      | a    |
|      |      |      |      |      |      |      | lues |
+------+------+------+------+------+------+------+------+
| Food |      |      |      |      |      |      | T    |
|      |      |      |      |      |      |      | here |
|      |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | h    |
|      |      |      |      |      |      |      | ould |
|      |      |      |      |      |      |      | be   |
|      |      |      |      |      |      |      | no   |
|      |      |      |      |      |      |      | mi   |
|      |      |      |      |      |      |      | s    |
|      |      |      |      |      |      |      | sing |
|      |      |      |      |      |      |      | v    |
|      |      |      |      |      |      |      | a    |
|      |      |      |      |      |      |      | lues |
+------+------+------+------+------+------+------+------+

**Comment: Finish moving the values up into the table**

| Tube \| Tube (1-12) that is used for each animal in each CTmax assay \| \| \| categorical \| \| 1-12 \| \|
| Thermometer \| Thermometer that is used for recording temperature during each CTmax assay \| \| \| Numeric \| ID \| \| \|
| Water Bath \| Water bath that is used as an environment for each CTmax assay \| \| \| Numeric \| ID \| \| \|
| Start Time \| Time that the water heater is plugged in and the experiment is officially started \| independent \| Questions 1 & 2 \| Numeric \| Military time \| \| \|
| Acclimation Day \| Day that each dish has been acclimating, day 0 is the day that they are moved to their respective incubators for acclimation \| independent \| Question/Objective 1, 2 \| Numeric \| Days \| 0-7 \| \|
| Experiment Date \| Date that the experiment is conducted \| \| \| Numeric \| DD/MM/YYYY \| \| \|
| Experimental Replicate \| Replicate that the experiment is occurring \| \| \| Numeric \| \| 0-5 \| \|
| Food \| Type of phytoplankton used to feed copepods, as well as the amount fed and frequency of feedings \| independent \| Drops/cell count? \| Numeric \\

## Study Design

**Comment: This section needs to be completed and cleaned up.**

Species: Skistodiaptomus pallidus

Cultures: Centennial Park; Lowell Canal if extended

Generation: F\>3

Treatments: 16C (Control), 22C (Warm)

MP Treatments: None, Present **Comment: We need a target concentration
of microplastics (Undecided)**

Trait Measurement: CTmax

Replicates: 3 Animals/dish = 40 Total animals needed = 100 (x/replicate)

3 experimental replicates and 4 CTmax assays

**Comment: Careful about what constitutes a replicate here - The number
of CTmax measurements per treatment is important, the number of
experimental replicates these values will be measured across is also
important. The experimental details (number of animals per dish, how
many dishes per treatment, total number of dishes, total number of
animals needed per experimental replicate) can then be added in.**

1.  Animals are collected from field and brought to lab.
2.  On setup day X adult females are selected from the lab culture and
    are evenly split into four different dishes with XmL of DIO and
    \~0.5mL-1.5mL C. ozolini.
3.  By the end of setup there will be four dishes: N+C, N+W, MP+C, MP+W,
    and each dish will have X animals. Equation used to get \#
    animals/dish: Animals/dish = ((# of assays \* \# of tubes)/# of
    dishes) + (0.5 \* \# of assays) **Comment: Initial CTmax
    measurements?**
4.  Dishes are given their respective amounts of MPs.
5.  Each dish is placed into their respective incubators, a temperature
    sensor is also placed in the incubators in a dish with 150mL of tap
    water to closely monitor the internal temperatures of the incubators
    (in the incubator there are two shelves, the temperature treatments
    are always on the same shelf as one another but alternate every
    replicate, also the incubator that is used as the control or the
    warm alternates every replicate).
6.  On day 7, 4 CTmax assays are ran using 2-3 animals from each dish in
    each assay. Tube placements for each assay are randomized using
    Skisto_LARA/Scripts/00_tube_assignments.R **Comment: Details need to
    be project specific. Also, we should plan on imaging the copepods
    after CTmax experiments are completed.**
7.  This is replicated 3 times. **Comment: We should be clear here - are
    the CTmax assays replicated 3 times on Day 7, or is the entire
    experiment replicated three times?**

**Comment:** Consider including a schematic or diagram. This could be an
embedded image, or an encoded diagram (e.g. Quarto includes native
support for [mermaid
diagrams](https://quarto.org/docs/authoring/diagrams.html#overview)).

## Statistics

### Data Processing

Data is processed in the controller script: - Pop = "thermometer" is
filtered out - CTmax values \< 34.5 are filtered out - acc_hours is
defined - datetime is mutated to fit our date and time format

**Comment: Here again, this section needs to be tailored to the
project - this is relevant to other work, but doesn't necessarily fit
for this project. Think through what will need to be done for this
project specifically.**

### Key Summary Statistics

+-------------------------------------+-----------------------+
| Summary Statistic                   | Calculated For Which  |
|                                     | Groups                |
+=====================================+=======================+
| Mean +/- Standard Error             | CTmax for each        |
|                                     | treatment: N+C, N+W,  |
|                                     | M P+C, MP+W. CTmax    |
|                                     | for each treatment +  |
|                                     | thermal tolerance,    |
|                                     | how it changes over   |
|                                     | the course of the     |
|                                     | experiment, how the   |
|                                     | mean of rate of       |
|                                     | acclimation is a      |
|                                     | cross treatments      |
+-------------------------------------+-----------------------+
| (How are we going to answer these   |                       |
| things?: Mean standard error: Think |                       |
| through what is needed)             |                       |
+-------------------------------------+-----------------------+

### Statistical Tests of Hypotheses

**Comment: 2. Restate the hypotheses. You might
also need to describe the statistical model for the first hypothesis.**

Hypothesis 1: 

-  Tests of assumptions:

-   How model fit will be evaluated: Using the performance package in R

-   Post-hoc tests: The CTmax of the no-MP and MP-present groups will be
    compared at each acclimation temperature. Support for this
    hypothesis would appear as consistently higher CTmax in MP-present
    animals.

-   Caveats/Caution when interpreting results: This design is limited to
    two stressors, other potentially interacting factors (e.g., food
    availability, oxygen levels, pollutants) are not accounted for and
    could influence thermal tolerance in ways this experiment cannot
    detect. (specify where that might be a problem)

-   Handling missing values: Any missing values will not be included in
    final data.
    
Hypothesis 2:

-   Tests of assumptions:

-   How model fit will be evaluated: Using the performance package in R

-   Post-hoc tests:

-   Caveats/Caution when interpreting results:

-   Handling missing values:



    Notes: Simplify: To refine we are missing the middle, what are we
    using to do this

    Post-hoc test (after the fact test): Is there a significant
    difference between treatments (group means), Slops (acclimation)






### Alternative Approaches

There are always different ways to analyze data.

This section should outline potential alternative approaches that could
be needed (e.g. when assumptions of planned analyses are not met).

## Key Figures

This section is relatively speculative. It can, however, be helpful to
have a section where you outline the expected tables and figures that
might be important to display based on the planned questions, analyses,
hypotheses, etc.
